dist: xenial
services:
 - mongodb
 - redis
sudo: false
language: python
cache: pip
python:
  - 3.7
before_script: "pip install -r requirements.txt"
script:
  - "python manage.py test"
  - "python manage.py lint"
